server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Permite enrutar automáticamente a servicios registrados en Eureka usando lb://SERVICE-NAME
      routes:
      # TODO: Configurar rutas para products-service y orders-service

# Configurar la URL del servidor Eureka al que el Gateway se registrará
# y desde el cual descubrirá servicios
# Los estudiantes deben asegurarse que esta URL apunta correctamente al eureka-server
# (por defecto http://localhost:8761/eureka)
eureka:
  client:
    service-url:
      defaultZone:
